### ISSUE TITLE
AttributeError: The input DataFrame must contain only integers, but non-ints were detected.

### ISSUE THREAD

**Issue by jmrichardson** [arvkevi/disarray#4]
Hi, I am getting this error:

```
cm
Out[10]: 
array([[ 81,   0, 147],
       [ 35,   0,  66],
       [ 32,   0, 199]], dtype=int64)
df = pd.DataFrame(cm)
df.da.sensitivity
```

Error:

```
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-5de582cdc042>", line 1, in <module>
    df.da.TP
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\pandas\core\generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\pandas\core\accessor.py", line 187, in __get__
    accessor_obj = self._accessor(obj)
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\disarray\__init__.py", line 11, in __init__
    self._validate(pandas_obj)
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\disarray\__init__.py", line 25, in _validate
    "The input DataFrame must contain only integers, but non-ints were detected."
AttributeError: The input DataFrame must contain only integers, but non-ints were detected.
```

**Comment by arvkevi** [comment]
Hi, @jmrichardson thank you for checking out disarray!

I had trouble reproducing the error you posted. I just brought up a quick jupyter notebook on [binder](https://mybinder.org/v2/gh/arvkevi/disarray/master) and ran a couple of cells -- it seemed to work ok.

Can you provide more details about the error? Maybe the surrounding code?
<img width="728" alt="Screen Shot 2020-09-14 at 3 43 31 PM" src="https://user-images.githubusercontent.com/9151717/93130824-16265580-f6a1-11ea-839a-bcc50b3a5868.png">

**Comment by raulsenaferreira** [comment]
I have the same issue:
```
import numpy as np
import disarray
import pandas as pd

a = [[ 81,   0, 147], [ 35,   0,  66], [ 32,   0, 199]]
df = pd.DataFrame(a)
print(df.da.sensitivity)
```

> "The input DataFrame must contain only integers, but non-ints were detected."
AttributeError: The input DataFrame must contain only integers, but non-ints were detected.

**Comment by arvkevi** [comment]
Hi @raulsenaferreira, thanks for posting the issue. Pull requests are welcome!

Before you submit the pull request, can you share your Python version? And did you install `disarray` using `pip` or did you install it by cloning the repository? The PyPI code is outdated. I need to cut a new release to PyPI, so that `pip install disarray` is even with the GitHub code. However, I just tried both installation methods and could not reproduce the error, so I'm curious to hear about your setup.

**Comment by arvkevi** [comment]
There is a new version of `disarray` on PyPI, you could try `pip install --upgrade disarray` and see if that solves the issue. But I'm still interested to hear about your Python environment.

**Comment by ashersuman** [comment]
I also had the same issue.  What fixed the issue for me was adding "dtype = int" when building the pandas dataframe.
`df = pd.DataFrame(cm, index=classes, columns=classes, dtype=int)`

**Comment by arvkevi** [comment]
Hi, @ashersuman, thanks for posting a workaround. Can you please share your Python environment? I cannot reproduce this error and everyone else above has ignored my request to share their environment, so it's difficult to debug.

Can you post the version of Python you are using? 
How you installed Python (conda or brew or something else)?
Can you post the output of `pip freeze`?

Thanks again!

**Comment by ashersuman** [comment]
Yeah sure! I was also unable to understand why this was happening on my system. I tried on binder and it worked perfectly there.
`conda version : 4.9.2`
`python version : 3.6.12.final.0`
I am on  a win64 machine so I use installer for anaconda.

`anaconda-client==1.7.2
anaconda-navigator==1.9.12
anaconda-project==0.8.3
conda==4.9.2
h5py==2.10.0
jupyter==1.0.0
jupyterlab==2.2.6
numpy==1.19.2
pandas==1.1.5
python-dateutil==2.8.1
pytz==2020.5
six==1.15.0`

**Comment by arvkevi** [comment]
Thanks, @ashersuman it was a bug specific to Windows. Explicitly setting the type when instantiating the DataFrame seems to work.

**Comment by arvkevi** [comment]
There is no real _fix_ for this issue. I confirmed (in #8) that unittests failed on Windows OS. So, I added comments in the README to inform Windows users that they need to explicitly set `dtype=int` when instantiating a `DataFrame`.
